In [74]:
# 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

import pandas as pd

tb = pd.read_csv("../Original data/tb.csv")

cols = list(tb.columns)
# tb = tb.dropna(axis=1, how='all', subset=cols[2:])
tb.head(10)

,iso2,year,new_sp,new_sp_m04,new_sp_m514,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,...,new_sp_f04,new_sp_f514,new_sp_f014,new_sp_f1524,new_sp_f2534,new_sp_f3544,new_sp_f4554,new_sp_f5564,new_sp_f65,new_sp_fu
0,AD,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AD,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AD,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AD,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AD,1993,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,AD,1994,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,AD,1996,8.0,NaN,NaN,0.0,0.0,0.0,4.0,1.0,...,NaN,NaN,0.0,1.0,1.0,0.0,0.0,1.0,0.0,NaN
7,AD,1997,17.0,NaN,NaN,0.0,0.0,1.0,2.0,2.0,...,NaN,NaN,0.0,1.0,2.0,3.0,0.0,0.0,1.0,NaN
8,AD,1998,1.0,NaN,NaN,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,AD,1999,4.0,NaN,NaN,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN

In [86]:
new_cols = []
for col in tb.columns[3:]:
    string = col.split('_')[2]
    sex = ""
    age = ""

    if string[0]=='m':
        sex += "Male"
    elif string[0]=='f':
        sex += "Female"

    age = string[1:]
    if age == "u":
        age = "age_unknown"
    elif age == "65":
        age = "65+"
    elif len(age) == 2:
        age = age[0] + '-' + age[1]
    elif len(age) == 3:
        age = age[0:1] + '-' + age[1:3]
    elif len(age) == 4:
        age = age[0:2] + '-' + age[2:4] 

    new_cols.append(sex + ' ' + age)
# print(new_cols)
# print(cols)

transform_cols = {}
for i in range(len(new_cols)):
    transform_cols[cols[i+3]] = new_cols[i]

print(transform_cols)
tb = tb.rename(columns=new_cols)

tb.head(10)

{'new_sp_m04': 'Male 0-4', 'new_sp_m514': 'Male 5-14', 'new_sp_m014': 'Male 0-14', 'new_sp_m1524': 'Male 15-24', 'new_sp_m2534': 'Male 25-34', 'new_sp_m3544': 'Male 35-44', 'new_sp_m4554': 'Male 45-54', 'new_sp_m5564': 'Male 55-64', 'new_sp_m65': 'Male 65+', 'new_sp_mu': 'Male age_unknown', 'new_sp_f04': 'Female 0-4', 'new_sp_f514': 'Female 5-14', 'new_sp_f014': 'Female 0-14', 'new_sp_f1524': 'Female 15-24', 'new_sp_f2534': 'Female 25-34', 'new_sp_f3544': 'Female 35-44', 'new_sp_f4554': 'Female 45-54', 'new_sp_f5564': 'Female 55-64', 'new_sp_f65': 'Female 65+', 'new_sp_fu': 'Female age_unknown'}

TypeError: 'list' object is not callable